version: '3.8'

services:
  web:
    build: ./
    command: python ./manage.py runserver
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
